2024-01-04 15:17:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef40d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6ef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6b30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef49d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef47c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9c60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef51e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea78e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6f20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef58d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef96c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5e40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef53c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef69e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef42b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea77c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5240>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9f60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef77c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5930>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefa530>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef53f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9ea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef6080>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:23:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4ac0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:23:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefae30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5ff0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7880>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4670>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7f70>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefa6e0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7ca0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5930>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef6080>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5900>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4bb0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef9660>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4490>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef47f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7700>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4970>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7940>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefa110>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7760>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7730>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7880>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5450>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefad10>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5330>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef44c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5750>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7970>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7700>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefa560>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7fa0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4970>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef6680>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4a00>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5330>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefb250>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef6b00>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef77f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef68f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4670>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7a30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef9e40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7d30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7910>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4f10>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5e40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefb520>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4af0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5450>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4790>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef56c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7cd0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefb4f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7640>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4c40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7760>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4340>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef4af0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefb220>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef53c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7880>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef75e0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef7520>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7940>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddefa530>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddea7a60>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef53f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9ddef5180>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5690>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb4c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7310>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef57e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea79a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb160>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4850>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7310>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb1f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4520>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef61a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7e80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9ff0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea6c80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6320>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4730>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4430>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4370>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefa980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7310>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef47f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5600>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4670>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea6c80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefaec0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7e20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5b70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5690>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4f40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefa440>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4520>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5000>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5360>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7af0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8f70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea67a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5030>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5300>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4f10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef69b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9000>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5f60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5510>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef68f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8880>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea67d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4400>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5e40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4f10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6b00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8e80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5600>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4820>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4970>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefa080>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7f10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4be0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5090>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7580>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef97b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef40d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7340>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7730>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7970>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb7c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4ac0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5660>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5210>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4d00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8280>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef52a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef73d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7850>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5930>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7670>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9900>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea78e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef56c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef56f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5b70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef44c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefbb50>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6890>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4490>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7940>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea66e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb6a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7a00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4310>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6dd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5870>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5f60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb040>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4c10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4190>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7490>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7520>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefae00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7df0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4880>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef58a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4ee0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8fa0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4340>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7400>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5390>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7ca0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8f70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea79d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6920>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7850>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5510>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6c20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef8fa0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7910>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef58d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea78b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef9570>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea67a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4b20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef63b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef7790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddefb250>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef4d00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef5030>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6800>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddef6ef0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9ddea7e20>: Failed to establish a new connection: [Errno 113] No route to host'))
