2023-11-13 09:20:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf0550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:20:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf0ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf1780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baa3850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf1150>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf0910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:25:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf2050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:25:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf2fb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf2710>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf1d20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf0b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf1540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf3190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baa3730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf13c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf0af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf1e70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf2410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf2c50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf04f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf1db0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf0df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf13c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baf33d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f463baa3940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
