2023-11-20 14:44:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738790040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738790b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738792d70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738793640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738791ff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738790a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738790670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738c0e1a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f872cb20730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87387936d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738790bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738791c60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738792e60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738793670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738792950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738792d10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738791e40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87387911b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:46:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8738790070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
