2023-11-13 09:21:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf9a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfb100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:21:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2944932b60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:25:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfb100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:25:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf8190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f294492c310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f294492d0c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfbdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf87c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf92d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf9ff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f294492c9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f294492c370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfaef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf8670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf9780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:26:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfad70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f294492cbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfbe50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cf8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfa2c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-13 09:27:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2958cfaaa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
