2024-01-04 15:17:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affca00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affeef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afffd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affeb30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6003d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafa00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601c60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd1e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcfa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600d00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affef20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6016c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd3c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe9e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafe50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafcd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affce80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6013f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd240>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601f60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafe50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afffa30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd5d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a602530>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601ea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affe080>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:23:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcac0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:23:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a602e30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affdff0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff880>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc670>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaff70>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a6026e0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afafca0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff2b0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affe080>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcdf0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcbb0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a601660>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affe050>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc7f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff700>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc970>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaf940>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a602110>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaf760>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff730>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff880>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd450>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a602d10>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd330>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc4c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd750>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff970>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaf700>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a602560>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaffa0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc970>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affe680>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc0d0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd330>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a603250>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affeb00>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff7f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affe8f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc670>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afafa30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a601e40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaffd0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff820>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcf10>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd630>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a603520>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcaf0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:31:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc8e0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd6c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afafcd0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a6034f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaf640>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcc40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff760>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affc340>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affcaf0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a603220>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd3c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affdff0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff5e0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afff520>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afaf940>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5a602530>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5afafa60>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:34:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a5affd180>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc430>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:34:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6034c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc640>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd7e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd8a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf9a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a603160>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafa30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc850>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc640>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6031f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc520>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afffa30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe1a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafe80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601ff0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaec80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe320>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc730>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff7f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc370>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a602980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc640>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc7f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd600>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc670>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaec80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a602ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafe20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd0f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcf40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a602440>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc520>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd000>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd360>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafaf0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600f70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afae7a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd030>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd300>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcf10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe9b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601000>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affdf60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd510>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe8f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf610>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600880>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afae7d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc400>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd630>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcf10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affeb00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600e80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd600>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc820>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc970>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafa30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601f00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaff10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcbe0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd090>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc760>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6017b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affca00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd7b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff340>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affedd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf970>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6037c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcac0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd660>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd210>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcd00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600280>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd2a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff3d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff850>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff2b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf670>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601900>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf8e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd6c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affda20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc4c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a603b50>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe890>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe050>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff910>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afae6e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6036a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaffa0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc310>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd390>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd870>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affdf60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a603040>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcc10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affebf0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff490>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcc40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafa30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a602e00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafc70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc880>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd9f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcee0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600fa0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc340>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff400>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affdc90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf640>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600f70>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf9d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd030>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff850>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd510>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affdc00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a600fa0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd7b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff820>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affd690>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf8b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a601570>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afaf7c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcb20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affc5b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afff790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe980>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a603250>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affcd00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe920>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affe800>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5affeef0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5afafe20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a5a6034c0>: Failed to establish a new connection: [Errno 113] No route to host'))
