2023-11-28 10:55:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7915510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7916f50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc754c3c9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d79152d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7915360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc754c3cca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e01ed630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e01ed540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc754c3cfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d79141c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e01ef5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d79145b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d79145e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d79142e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc754c3c760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e01ef5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e01ed720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc754c3cf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7915720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8e01ed8a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7914c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc754c3cf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
