2023-11-17 08:45:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae45e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae5810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8ea9baf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae52a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae47c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae60b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae6950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8ea9b730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae64a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae4670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae4f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae57b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae7220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae57b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f8eae4f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
