2023-12-14 13:38:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f87c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f97e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32abb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9210>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f89a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa080>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32ab9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa620>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9d80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f96f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9de0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fab00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32ab700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32face0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa380>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f90c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9b70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32abc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9f30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9f90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32abf40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9870>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f95a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32ab670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa650>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f82e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9600>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f92d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbc70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32ab6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f91b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f98d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32abdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32faa70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9f30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9930>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f94e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32faa70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29243d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32abb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f90c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f98a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f94e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32faa70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9e10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29246d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32abd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9b70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9bd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fba30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f85b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa9e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa9e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f85b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9d20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29246d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fab60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f96f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9fc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9e70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f98d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa260>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f98d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa650>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa1a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9f30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9ff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbe50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbdc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa1a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9240>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fafe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9b10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9600>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f95d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbe20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29257e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f82b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fadd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32faaa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29251b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9d50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fafb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925c60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f91e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925840>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925f60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa5c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9f30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925bd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9ff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f95a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29260b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbfa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9cf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32faf20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fba60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f93c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fafb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9660>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f88b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f86d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fba90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29243d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9270>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9a80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbc70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa770>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29254b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fba90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9a80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fafb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa2f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fba90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa2c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2926530>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa380>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbe50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9150>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2926830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa5f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9e40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa320>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2926980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9660>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbdf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29264a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fafb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f88e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9870>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9a80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29253f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29242b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29255a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f90f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f92a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbcd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2926260>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa620>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29261a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa3e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fba30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2926260>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f89a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29247c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa740>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29246a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa29247c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fafb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9ae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2926200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32faaa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa770>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2924250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fbb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f8850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fa260>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa2925510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32f9c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa32fb9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:26 | ERROR | m