2024-01-03 15:04:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129baf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e98d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bf40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea0b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e90f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eaa40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e95d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9e10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129a6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea320>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9e70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e96f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e92a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e88b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e97b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9ff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eae00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9f90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129a7a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea8c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eab60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eabf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e92d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e93c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e88e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9e10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9de0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9ba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9180>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea2f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9540>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9a80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ebbe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129baf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eafe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e97b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eada0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129ba00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eaad0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9a20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ebee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9ae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea800>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129b8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e96c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e97b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e87c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9270>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e98a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129a770>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eaa70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9a20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea3e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e89d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9090>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ec550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9f00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eb490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ec3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea0b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e9000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e8910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ec850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f5129bd60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512e82e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea7a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512ea140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f512eca60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
