2024-01-03 15:04:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c88e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c96f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cad10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca770>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:04:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c94e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c96c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb7c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:05:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c99c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cae90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9240>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca380>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca770>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:06:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1310f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c85e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1312a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1316f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca830>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:07:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c85e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93229282e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9ea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932ed32470>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1330a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb4f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca3b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:08:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9322928340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9fc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1315d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9322928f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1330a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cab60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932292b400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:09:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c98d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9300>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c81f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1312a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:10:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cab30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cba90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131150>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca0b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c94b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c81f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:11:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c93f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c88e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca7d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9cf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1312d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:12:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4caad0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cafe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca740>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9ae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932292aa70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:13:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9ba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbe50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cae60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9322929000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9090>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cb880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c8eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:14:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca1a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9322929bd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca1a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c99c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9d50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932ed32020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130af0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932292a4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cae60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbc70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbe80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:15:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131210>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4cbe20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4ca0b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c9c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f932e4c94e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-03 15:16:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132d10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
