2023-11-20 14:44:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde80d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde89d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde9270>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fd9b8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde8fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde86a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:44:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde9b10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fdea3b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fd9b910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fdea290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde99f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde8880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde9000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fdeac80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde95d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde8940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fde9930>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fdea200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:45:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fdea590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-20 14:46:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f334fd9b970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
