2023-12-14 13:38:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced8a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76c9fc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced1e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee9e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76c9e890>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:38:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee530>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecf70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced9c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced120>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee470>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceebc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76c9e890>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee620>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:39:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced270>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedcc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:40:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76c9fee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee260>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee770>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:41:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec8b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced2a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced7b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee080>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76c9ff40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:42:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced120>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced090>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecd90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceffd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee3e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedff0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedf60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:43:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced3c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced600>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedf30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cede70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:44:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced810>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cede10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76c9faf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee0e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:45:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecf40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced870>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedd80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763188e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedf60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee4a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:46:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee4a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedf60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee0b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefa90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:47:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced7e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefa60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee6e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceee90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:48:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee8f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee5f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee6e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763185e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced6f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:49:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee7a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceee90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763186d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced6f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee7a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:50:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced150>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceff10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced660>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced420>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:51:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cece80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecc70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedb40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:52:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceded0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee6e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763183a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceca00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763198a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:53:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced6f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763190f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefeb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cece80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee8c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef340>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:54:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee380>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedf90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763193f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced8a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceccd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:55:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319d20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee5c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedd20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecd60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cede40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763199c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced5a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:56:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceca90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319c90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced180>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced7e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:57:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee3b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763189d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee2c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedd80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedbd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:58:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced7e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319e40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedd80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee380>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763193c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 13:59:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefa00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced5a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee200>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced7e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a170>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:00:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefe20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee980>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedb40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefa00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763180a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:01:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceed40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedcc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced930>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319a80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced270>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:02:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a5f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee140>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced7e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced600>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763196f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedbd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedba0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:03:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cece80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a8f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced480>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedcc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceed40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced060>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a800>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecd00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:04:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced480>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631aa40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee440>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee6e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceee90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:05:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319900>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cede70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced6f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced360>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefe20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:06:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763198a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced4b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceeb30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cec7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef730>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:07:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763186a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceca30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedae0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced5a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:08:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceda80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced930>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee080>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedc90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab7631a1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:09:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceee90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefb50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76318700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced120>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefdf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced960>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:10:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceee90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee260>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319cf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cee530>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceed40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cedcc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cece50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced390>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76319ea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced960>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:11:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cefdf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cef160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ced120>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab763187c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76ceccd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-12-14 14:12:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab76cecc10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
