2024-01-04 15:17:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1308b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198458a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198453c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846230>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:17:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1302b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131840>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845b70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132ef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845e70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198456f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:18:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132d70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198464d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198460e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1315d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a133010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:19:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132d10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846500>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198463b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846620>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131750>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198460e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131030>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1302b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:20:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130a60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a133010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846d10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:21:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198447c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132d70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1312a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198467a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131720>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:22:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844a90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1316f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846e30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2024-01-04 15:23:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847520>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:23:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131030>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:23:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130130>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846950>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198444c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198453c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130730>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131210>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:24:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1305e0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198473d0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319844100>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846ef0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131150>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1316f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:25:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130e20>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319845c00>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846d10>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198462f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130670>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131090>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:26:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a133220>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319845840>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846380>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319845fc0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1302b0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a132d70>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:27:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846d40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198452a0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847ee0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130400>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130850>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131480>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:28:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846ad0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319845a20>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846e30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131240>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130f40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1300a0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:29:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319844e50>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198452a0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319845330>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130dc0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1313f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a133220>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:30:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198461a0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198471c0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846710>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130160>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130d30>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319844340>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:31:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847430>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319845d80>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130e50>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130130>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131600>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f93198468f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:32:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847010>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319844c40>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1316f0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130190>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a130e50>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847c70>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:33:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847430>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319846110>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a1308b0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a131210>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f931a133220>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9319847ac0>, 'Connection to 192.168.2.60 timed out. (connect timeout=5)'))
2024-01-04 15:34:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198468c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:34:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844100>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131720>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1302b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847220>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845db0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845f90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130a90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130880>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a133100>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:35:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847e20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845ff0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846a10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131120>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132f80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845720>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845db0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198478b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:36:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130ee0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130d90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845780>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844c10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846200>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130bb0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130520>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847400>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198472b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:37:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847eb0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131060>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131150>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844c10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845900>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130f40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845ab0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:38:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847640>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847700>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1305b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130490>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130550>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846050>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844a90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846cb0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131450>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:39:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131090>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844be0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847640>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847250>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130670>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130f40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847880>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:44 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845d20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845e40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:40:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1302e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1317b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130820>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198452d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198461a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:27 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847370>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1307f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130c10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130d90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847b80>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:41:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845d20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:04 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845a50>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130d00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130670>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198443a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198457e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846050>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1301f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:47 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131240>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1305e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:42:59 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846410>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844700>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845360>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130790>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130130>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130a90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845300>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:42 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198457e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845960>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:43:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1303a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130d00>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846e60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846890>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:19 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847400>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130e50>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1301c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846140>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198468c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:44:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845f60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:02 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130ee0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132dd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a132d10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198459c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846890>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847cd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:39 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131150>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1303a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844b50>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:45:57 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844250>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847e20>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:09 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130af0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130070>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:22 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130f40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845c60>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:34 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846260>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845b40>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131810>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:52 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131270>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:46:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1304c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198449d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844250>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:17 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846da0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131090>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:29 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131150>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198473d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844eb0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844040>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:47:54 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131210>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131600>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a131000>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:12 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93198447f0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319844a90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:24 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847010>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1312a0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:37 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a130940>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1302b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:49 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846bc0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:48:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847a30>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847c10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:07 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1316c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:14 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1313c0>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319846740>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319845b10>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:32 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9319847a90>: Failed to establish a new connection: [Errno 113] No route to host'))
2024-01-04 15:49:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.60', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f931a1309a0>: Failed to establish a new connection: [Errno 113] No route to host'))
