2023-11-28 10:55:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806a7df0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f51b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:55:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4940>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f6020>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f68c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806a7cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f6560>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5cc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f7190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f55a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5cf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:56:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f6410>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:03 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f6aa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:08 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806a78b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:13 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f6c80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:18 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f6350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:23 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:28 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5570>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:33 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5b70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:38 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806a7d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:43 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:48 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f4b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:53 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f5ea0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-28 10:57:58 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.2.144', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d806f69e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
