2023-11-17 08:45:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f740be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f7418d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f0cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:41 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f7407f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:46 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f7410f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:51 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f0820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:45:56 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f1f30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:01 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f2920>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:06 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f3880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:11 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f741840>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:16 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f74a9e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:21 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f25f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:26 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f16f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:31 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f894b2f1930>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-17 08:46:36 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='192.168.1.104', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f893f741780>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
